### ISSUE TITLE
some suggestion(poig)

### ISSUE THREAD

**Issue by poig** [mgg39/Quantum-youtube-channels#4]
https://www.youtube.com/@IPAMUCLA
https://www.youtube.com/@instituteforrobustquantums7668
https://www.youtube.com/@CAMOP_UW
https://www.youtube.com/@PsiQuantum
https://www.youtube.com/@ZapataAI
https://www.youtube.com/@centerforquantumnetworks

also feel free to explore https://github.com/poig/Qc_book_list for other quantum resources

**Comment by mgg39** [comment]
thanks @poig ! if you'd like you can create a pull request or otherwise I am happy to added it myself :)
